### ISSUE TITLE
Misc Todo

### ISSUE THREAD

**Issue by ben-marshall** [ben-marshall/sat-solver#1]
Infrastructure
 - [X] Codedocs Doxygen
 - [X] Read the docs

Parser
 - [X] Expression data structure
 - [X] Nested expression parsing

Implication Matrix
 - [X] Generate matrix based on size of expression tree
 - [X] Inserting tree into matrix
 - [X] Filling out of matrix from tree leaf to root.

Testing
 - [x] Coverage build.
 - [x] Coveralls integration.
 - [x] Random Testing framework.

Optimisation
 - [x] Setup profiling run
 - [x] OpenMP
